"""empty message

Revision ID: 30d757716943
Revises: 34957f3cf5f3
Create Date: 2025-11-02 18:49:39.128755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d757716943'
down_revision = '34957f3cf5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('work_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('work_days',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
