"""empty message

Revision ID: 34957f3cf5f3
Revises: dcc9c71b8a96
Create Date: 2025-10-30 20:56:20.983372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34957f3cf5f3'
down_revision = 'dcc9c71b8a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
