"""make appointment center_id nullable with ondelete SET NULL

Revision ID: 63105ba5700f
Revises: 7d7829d1505c
Create Date: 2026-03-20 15:53:59.706092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63105ba5700f'
down_revision = '7d7829d1505c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('center_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('appointments_center_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'centers', ['center_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointments_center_id_fkey'), 'centers', ['center_id'], ['id'])
        batch_op.alter_column('center_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
