"""add clinical_records table

Revision ID: 7d7829d1505c
Revises: 2fe2c31e950c
Create Date: 2026-03-19 21:43:05.377386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7829d1505c'
down_revision = '2fe2c31e950c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('diagnosis', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    with op.batch_alter_table('clinical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_records_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_records_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_records_doctor_id'))

    op.drop_table('clinical_records')
    # ### end Alembic commands ###
