"""add medical_reports table

Revision ID: b10727d556a3
Revises: 55c5c9cc87f6
Create Date: 2026-03-22 15:41:32.640017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10727d556a3'
down_revision = '55c5c9cc87f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_reports_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reports_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_doctor_id'))

    op.drop_table('medical_reports')
    # ### end Alembic commands ###
